language: python
fast_finish: true
sudo: required  # temporarily needed for xenial + 3.7 (July 2018)


python:
  - 3.6
  - 3.7

os:
  - linux
  
dist: xenial
group: travis_latest

git:
  depth: 3
  
addons:
  apt:
    packages:
      - octave
      - octave-signal

install: pip install -e .[tests]

# Fake X11 server
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - pytest -v
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then 
    pytest --cov;
    coveralls; 
    fi
