language: python
fast_finish: true

python:
  - 3.6

os:
  - linux
  
dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3
  
addons:
  apt:
    packages:
      - octave
      - octave-signal

install: pip install -e .[tests]

# Fake X11 server
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: coverage run tests/test.py -v

after_success: coveralls
